### ISSUE TITLE
localStorage is not defined

### ISSUE THREAD

**Issue by DenisCarriere** [wharfkit/session#55]
Similar code to: https://github.com/wharfkit/web-renderer/issues/15

Platform: NextJS 13

## Code example

```typescript
"use client";
import { SessionKit } from '@wharfkit/session';
import { WalletPluginAnchor } from '@wharfkit/wallet-plugin-anchor';
import WebRenderer from '@wharfkit/web-renderer';
import { useEffect, useState } from "react";

const eos = {
  id: 'aca376f206b8fc25a6ed44dbdc66547c36c6c33e3a119ffbeaef943642f0e906',
  url: 'https://eos.greymass.com',
}

export default function Login() {
  const [kit, setKit] = useState<SessionKit|null>(null);
  useEffect(() => {
    const sessionKit = new SessionKit({
      appName: "names",
      chains: [eos],
      ui: new WebRenderer(),
      walletPlugins: [new WalletPluginAnchor()],
    })
    setKit(sessionKit);
  }, [])
}
```

## ❌  Error message

```
error - unhandledRejection: Error [ReferenceError]: localStorage is not defined
    at BrowserLocalStorage.<anonymous> (/Users/denis/Github/ens-ui/node_modules/@wharfkit/session/lib/session.js:758:13)
    at Generator.next (<anonymous>)
    at /Users/denis/Github/ens-ui/node_modules/tslib/tslib.js:167:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/Users/denis/Github/ens-ui/node_modules/tslib/tslib.js:163:16)
    at BrowserLocalStorage.read (/Users/denis/Github/ens-ui/node_modules/@wharfkit/session/lib/session.js:757:22)
    at makeSettingsStore (webpack-internal:///(sc_client)/./node_modules/@wharfkit/web-renderer/lib/web-renderer.js:3008:13)
    at eval (webpack-internal:///(sc_client)/./node_modules/@wharfkit/web-renderer/lib/web-renderer.js:3026:18)
    at (sc_client)/./node_modules/@wharfkit/web-renderer/lib/web-renderer.js (/Users/denis/Github/ens-ui/.next/server/app/[locale]/page.js:6463:1)
    at __webpack_require__ (/Users/denis/Github/ens-ui/.next/server/webpack-runtime.js:33:43)
    at eval (webpack-internal:///(sc_client)/./components/Login/Login.tsx:20:80)
    at (sc_client)/./components/Login/Login.tsx (/Users/denis/Github/ens-ui/.next/server/app/[locale]/page.js:1668:1)
    at __webpack_require__ (/Users/denis/Github/ens-ui/.next/server/webpack-runtime.js:33:43)
    at eval (webpack-internal:///(sc_client)/./components/Navbar.tsx:13:70)
    at (sc_client)/./components/Navbar.tsx (/Users/denis/Github/ens-ui/.next/server/app/[locale]/page.js:1679:1)
    at __webpack_require__ (/Users/denis/Github/ens-ui/.next/server/webpack-runtime.js:33:43)
    at requireModule (/Users/denis/Github/ens-ui/node_modules/next/dist/compiled/react-server-dom-webpack/cjs/react-server-dom-webpack-client.edge.development.js:148:32)
    at initializeModuleChunk (/Users/denis/Github/ens-ui/node_modules/next/dist/compiled/react-server-dom-webpack/cjs/react-server-dom-webpack-client.edge.development.js:481:17)
    at readChunk (/Users/denis/Github/ens-ui/node_modules/next/dist/compiled/react-server-dom-webpack/cjs/react-server-dom-webpack-client.edge.development.js:311:7)
    at renderLazyComponent (/Users/denis/Github/ens-ui/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.edge.development.js:8927:19)
    at renderElement (/Users/denis/Github/ens-ui/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.edge.development.js:9038:11)
    at renderNodeDestructiveImpl (/Users/denis/Github/ens-ui/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.edge.development.js:9115:11)
    at renderNodeDestructive (/Users/denis/Github/ens-ui/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.edge.development.js:9087:14)
    at renderNode (/Users/denis/Github/ens-ui/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.edge.development.js:9291:12)
    at renderChildrenArray (/Users/denis/Github/ens-ui/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.edge.development.js:9243:7)
    at renderNodeDestructiveImpl (/Users/denis/Github/ens-ui/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.edge.development.js:9151:7)
    at renderNodeDestructive (/Users/denis/Github/ens-ui/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.edge.development.js:9087:14)
    at renderNode (/Users/denis/Github/ens-ui/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.edge.development.js:9291:12)
    at renderChildrenArray (/Users/denis/Github/ens-ui/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.edge.development.js:9243:7)
    at renderNodeDestructiveImpl (/Users/denis/Github/ens-ui/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.edge.development.js:9151:7)
    at renderNodeDestructive (/Users/denis/Github/ens-ui/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.edge.development.js:9087:14)
    at renderContextProvider (/Users/denis/Github/ens-ui/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.edge.development.js:8913:3)
    at renderElement (/Users/denis/Github/ens-ui/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.edge.development.js:9026:11)
    at renderNodeDestructiveImpl (/Users/denis/Github/ens-ui/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.edge.development.js:9115:11)
    at renderNodeDestructive (/Users/denis/Github/ens-ui/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.edge.development.js:9087:14)
    at renderIndeterminateComponent (/Users/denis/Github/ens-ui/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.edge.development.js:8768:7)
    at renderElement (/Users/denis/Github/ens-ui/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.edge.development.js:8949:7)
    at renderNodeDestructiveImpl (/Users/denis/Github/ens-ui/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.edge.development.js:9115:11)
    at renderNodeDestructive (/Users/denis/Github/ens-ui/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.edge.development.js:9087:14)
    at finishClassComponent (/Users/denis/Github/ens-ui/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.edge.development.js:8670:3)
    at renderClassComponent (/Users/denis/Github/ens-ui/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.edge.development.js:8678:3)
    at renderElement (/Users/denis/Github/ens-ui/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.edge.development.js:8946:7)
    at renderNodeDestructiveImpl (/Users/denis/Github/ens-ui/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.edge.development.js:9115:11)
    at renderNodeDestructive (/Users/denis/Github/ens-ui/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.edge.development.js:9087:14)
    at renderIndeterminateComponent (/Users/denis/Github/ens-ui/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.edge.development.js:8768:7)
    at renderElement (/Users/denis/Github/ens-ui/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.edge.development.js:8949:7)
    at renderNodeDestructiveImpl (/Users/denis/Github/ens-ui/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.edge.development.js:9115:11)
    at renderNodeDestructive (/Users/denis/Github/ens-ui/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.edge.development.js:9087:14)
    at renderElement (/Users/denis/Github/ens-ui/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.edge.development.js:8975:9)
    at renderNodeDestructiveImpl (/Users/denis/Github/ens-ui/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.edge.development.js:9115:11) {
  digest: undefined
}
```

**Comment by aaroncox** [comment]
This looks to be an issue with how nextjs does server side rendering, and how the WebRender uses localStorage immediately when you import it. 

I'm looking for a solution on our side but did discover that if you move the import into the `useEffect` call, it no longer throws this error.

```ts
"use client";
import { SessionKit } from '@wharfkit/session';
import { WalletPluginAnchor } from '@wharfkit/wallet-plugin-anchor';
import { useEffect, useState } from "react";
 
const eos = {
  id: 'aca376f206b8fc25a6ed44dbdc66547c36c6c33e3a119ffbeaef943642f0e906',
  url: 'https://eos.greymass.com',
}

export default function Login() {
  const [kit, setKit] = useState<SessionKit|null>(null);
  useEffect(() => {
    const loadWharf = async () => {
        const {WebRenderer} = await import('@wharfkit/web-renderer')
        const sessionKit = new SessionKit({
          appName: "names",
          chains: [eos],
          ui: new WebRenderer(),
          walletPlugins: [new WalletPluginAnchor()],
        })
        setKit(sessionKit);
    }
    loadWharf()
  }, [])
  return <span>Login</span>
}
```

I'll close this and provide an update once I can prevent `localStorage` from being accessed immediately upon running.
